 - name: Build executables or extension modules from Python projects 
  uses: Nuitka/Nuitka-Action@v1.1
  with:
    # Directory to run nuitka in if not top level
    working-directory: # optional, default is .
    # Version of nuitka to use, branches, tags work
    nuitka-version: # optional, default is main
    # Path to python script that is to be built.
    script-name: brevgenerator/kunddata_till_brev.py 
    # Github personal access token of an account authorized to access the Nuitka-commercial repo
    access-token: # optional
    # Create an importable binary extension module executable instead of a program. Defaults to off.
