name: Package Application
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Package Application
        run: |
          pyinstaller --onefile brevgenerator/kunddata_till_brev.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: packaged-app
          path: dist/

      - name: Generate Tag
        id: generate_tag
        run: echo "::set-output name=tag::v0.0.1"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.generate_tag.outputs.tag }}
          release_name: Release ${{ steps.generate_tag.outputs.tag }}
          draft: false
		  overwrite: true
		  prerelease: false
