name: Build scripts

on: push

jobs:
  autodako:
    name: build-autodako
    runs-on: windows-latest
    steps:
      - name: Generate Tag
        id: generate_tag
        run: echo "::set-output name=tag::$(date +'%Y%m%d%H%M')"
      
      - name: Checkout
        uses: actions/checkout@v2

      - name: Verify Icon File
        run: |
          if [ ! -f autodako/edvin.ico ]; then
            echo "Icon file not found!"
            exit 1
          fi

      - name: Ahk2Exe
        uses: CCCC-L/Action-Ahk2Exe@main
        with:
          in: autodako/autodako.ahk
        working-directory: autodako

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.generate_tag.outputs.tag }}
          release_name: Release ${{ steps.generate_tag.outputs.tag }}
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./autodako/autodako.exe
          asset_name: autodako.exe
          asset_content_type: application/octet-stream