name: Build scripts

on: push

jobs:

  autodako:
    name: build-autodako
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ahk2Exe
        uses: nekocodeX/GitHub-Action-Ahk2Exe@main
        with:
          in: autodako/autodako.ahk

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: autodako.exe
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}